dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from dingo.views import logout_view  
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView
from dingo.api import router

urlpatterns = [
   path('admin/', admin.site.urls),
   path('maths/', include("maths.urls")),
   path('greetings/', include('greetings.urls')), 
   path('sessions/', include("sessions.urls")),
   path('posts/', include("posts.urls")),
   path('',  include("home.urls") ),
   path('about/',  include("about.urls") ),
   path('contact/',  include("contact.urls") ),
   
   path('accounts/logout/', logout_view, name='logout'),
   path('accounts/', include('django.contrib.auth.urls')),
   path('admin/', admin.site.urls),
   path('about/', TemplateView.as_view(template_name="about/about.html")),

   path('grappelli/', include('grappelli.urls')),
   path('admin/', admin.site.urls),

   path('api/v1/', include(router.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import main
from django.http import HttpResponse
urlpatterns = [
    path('', main,name="home"),
]

posts/urls.py
from django.urls import path
from django.views.generic import ListView
from posts.models import Post
from posts.views import post_list, post_detail, author_list, author_detail

app_name = "posts"

urlpatterns = [
   path('', post_list, name="list"),
   path('<int:pk>', post_detail, name="details"),
   path('authors', author_list, name="authors"),
   path('authors/<int:id>', author_detail, name="author"),
   path('list', ListView.as_view(model=Post), name="posts_list")
]

posts/models.py
from django.db import models

class Author(models.Model):
    nick = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    def __str__(self):
        return self.nick
class Post(models.Model):
    title = models.CharField(max_length=255)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='photos/%Y/%m/%d')
    tags = models.ManyToManyField("posts.Tag")
    def __str__(self):
        return self.title
class Tag(models.Model):
   word = models.CharField(max_length=50, unique=True)
   created = models.DateTimeField(auto_now_add=True)

posts/forms.py
from django import forms
from .models import Post, Author

class PostForm(forms.ModelForm):
   class Meta:
       model = Post
       fields = "__all__"
       fields = ["title", "content", "author", "image", "tags"]
class AuthorForm(forms.ModelForm):
    class Meta:
        model = Author
        fields = "__all__"

posts/views.py
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Author
from .forms import PostForm, AuthorForm


def post_list(request):
    posts = Post.objects.all()
    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            return redirect('post_list')
    else:
        form = PostForm()
    return render(request, 'posts/post_list.html', {'posts': posts, 'form': form})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'posts/post_detail.html', {'post': post})

def post_add(request):
    if request.method == 'POST':
        form = PostForm(data=request.POST, files=request.FILES)  # <- tu wrzucasz
        if form.is_valid():
            form.save()
            return redirect('post_list')
    else:
        form = PostForm()
    return render(request, 'posts/post_form.html', {'form': form})

def author_list(request):
    authors = Author.objects.all()
    return render(request, 'posts/author_list.html', {'authors': authors})

def author_add(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('author_list')
    else:
        form = AuthorForm()
    return render(request, 'posts/author_form.html', {'form': form})

def author_detail(request, pk):
    author = get_object_or_404(Author, pk=pk)
    return render(request, 'posts/author_detail.html', {'author': author})

templates/posts/author_detail.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
    <<h2>{{ author.nick }}</h2>
<p>Email: {{ author.email }}</p>
<a href="{% url 'author_list' %}">⟵ Wróć do listy autorów</a>
{% endblock %}

templates/posts/author_form.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
  <h2>Dodaj autora</h2>
<form method="post">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit">Zapisz</button>
</form>
<a href="{% url 'author_list' %}">⟵ Wróć do listy autorów</a>
<h2>{{ author.nick }}</h2>
<p>Email: {{ author.email }}</p>
<a href="{% url 'author_list' %}">⟵ Wróć do listy autorów</a>


{% endblock %}

templates/posts/author_list.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<h1>Lista autorów</h1>
<ul>
  {% for author in authors %}
    <li><a href="{% url 'author_detail' author.pk %}">{{ author.nick }}</a></li>
  {% endfor %}
</ul>
<a href="{% url 'author_add' %}">Dodaj autora</a>


{% endblock %}

templates/posts/post_detail.html
<h1>{{ post.title }}</h1>
<h2>{{ post.author.nick }} | {{ post.created }}</h2>
<p>
   {{ post.content }}
</p>
<div><img src="{{ post.image.url }}"></div>

templates/posts/post_form.html
{% extends "home/base.html" %}
{% load static %}

{% block content %}
<h2>Dodaj nowy post</h2>
<form method="POST" enctype='multipart/form-data'>
   {% csrf_token %}
{{ form.as_p }}
   <input type="submit" value="Dodaj">
</form>
<a href="{% url 'post_list' %}">⟵ Wróć do listy postów</a>


{% endblock %}

templates/posts/post_list.html
{% extends "../main.html" %}

{% block title %}Posty{% endblock %}

{% load bootstrap4 %}

{% block content %}
   <nav aria-label="breadcrumb">
       <ol class="breadcrumb">
           <li class="breadcrumb-item"><a href="{% url 'home' %}">Strona główna</a></li>
           <li class="breadcrumb-item active" aria-current="page">Posty</li>
       </ol>
   </nav>

   <div class="row">
       <div class="col-6">
           <table class="table">
               <tr>
                   <th>Tytuł</th>
                   <th>Autor</th>
                   <th>Data</th>
               </tr>
               {% for p in posts %}
                   <tr>
                       <td><a href="{% url "posts:details" p.id %}">{{ p.title }}</a></td>
                       <td>{{ p.author.nick }}</td>
                       <td>{{ p.created }}</td>
                   </tr>
               {% endfor %}
           </table>
       </div>
   </div>
{% endblock %}