dingo/urls.py
from django.contrib import admin
from django.urls import path, include
from dingo.views import logout_view  
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from django.views.generic import TemplateView
from dingo.api import router

urlpatterns = [
   path('admin/', admin.site.urls),
   path('maths/', include("maths.urls")),
   path('greetings/', include('greetings.urls')), 
   path('sessions/', include("sessions.urls")),
   path('posts/', include("posts.urls")),
   path('',  include("home.urls") ),
   path('about/',  include("about.urls") ),
   path('contact/',  include("contact.urls") ),
   
   path('accounts/logout/', logout_view, name='logout'),
   path('accounts/', include('django.contrib.auth.urls')),
   path('admin/', admin.site.urls),
   path('about/', TemplateView.as_view(template_name="about/about.html")),

   path('grappelli/', include('grappelli.urls')),
   path('admin/', admin.site.urls),

   path('api/v1/', include(router.urls)),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

greetings/urls.py
from django.urls import path
from .views import *
from django.http import HttpResponse
app_name = "greetings"
urlpatterns = [
    path('', greetings, name="greetings"),
    path('<imie>/', lambda request, imie: HttpResponse("Hello "+imie+"!")),
]

home/urls.py
from django.urls import path
from .views import main
from django.http import HttpResponse
urlpatterns = [
    path('', main,name="home"),
]

maths/urls.py
from django.urls import path, include
from .views import *
app_name="maths"
urlpatterns = [
   path('', math),
   path('add/<int:a>/<b>', add),
   path('sub/<int:a>/<b>', sub),
   path('mul/<int:a>/<b>', mul),
   path('div/<int:a>/<b>', div),
   path('histories/', maths_list, name="list"),
   path('histories/<int:id>', math_details, name="details"),
   path('results/', results_list, name="results"),
   path('accounts/', include('django.contrib.auth.urls')),
]

posts/urls.py
from django.urls import path
from django.views.generic import ListView
from posts.models import Post
from posts.views import post_list, post_detail, author_list, author_detail

app_name = "posts"

urlpatterns = [
   path('', post_list, name="list"),
   path('<int:pk>', post_detail, name="details"),
   path('authors', author_list, name="authors"),
   path('authors/<int:id>', author_detail, name="author"),
   path('list', ListView.as_view(model=Post), name="posts_list")
]

templates/main.html
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>{% block title %}Title{% endblock %}</title>

    {% load static %}

    {# Load CSS and JavaScript #}
    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    <link rel="stylesheet" href="{% static 'dingo/styles/style.css' %}">


</head>

<body>
    <div id="content">
        <div id="header">
            <div class="start"><img src="{% static 'maths/img/logo3.svg' %}">
                DINGO
            </div>
           <nav>
    <a href="{% url 'home' %}">Strona główna</a>
    <a href="{% url 'greetings:greetings' %}">Strona powitalna</a>
    <a href="{% url 'posts:list' %}">Posty</a>
    <a href="{% url 'maths:list' %}">Maths</a>
    
    {% if user.is_authenticated %}
        <p class="nav-link">
            {{ user.username }} |
            <form method="post" action="{% url 'logout' %}" style="display:inline;">
                {% csrf_token %}
                <button type="submit" class="btn btn-link nav-link"
                    style="padding: 0; border: none; background:none;">
                    logout
                </button>
            </form>
        </p>
    {% else %}
        <a class="nav-link" href="{% url 'login' %}">login</a>
    {% endif %}
</nav>


        </div>

        {% bootstrap_messages %}
        <div id="inner-content">
            {% block content %}
            To jest blok kodu. W innych szablonach możemy go nadpisać
            {% endblock %}
        </div>
    </div>
</body>

</html>